### ISSUE TITLE
Adding microbyte about getting started with MongoDB

### ISSUE THREAD

**Issue by manishdasa100** [Crio-Bytes/Database#2]
**MicroByte Title:** Everything  about getting started with MongoDB.

**Domain:** NoSQL Database operation.

**Scope of learning for learners:** Learners keen to learn about nosql database and MongoDB as one of its kind can get hands on with it and know the nitty-gritty of MongoDB and NoSql databases. 

**Activities:** The microbyte will contain activities like - 
- Running mongoDB locally as well as remotely. 
- Knowing about mongoDB clients and drivers. 
- Basics about mongoDB.
- Queries in mongoDB.
- CRUD operations in mongoDB.
- When to use mongoDB(SQL vs NoSQL)

**Comment by Kevinpaulose05** [comment]
Pls follow all guidelines as mentioned in the .github folder. Make the project as interactive as possible keeping in mind the max time needed to go through ur microbyte should be at most 1hr.
All the Best

**Comment by YourAKShaw** [comment]
> **MicroByte Title:** Everything about getting started with MongoDB.
> 
> **Domain:** NoSQL Database operation.
> 
> **Scope of learning for learners:** Learners keen to learn about nosql database and MongoDB as one of its kind can get hands on with it and know the nitty-gritty of MongoDB and NoSql databases.
> 
> **Activities:** The microbyte will contain activities like - running mongoDB locally as well as remotely, knowing about mongoDB clients and drivers, basics about mongoDB, queries in mongoDB, CRUD operations in mongoDB, when to use mongoDB(SQL vs NoSQL)

Kindly segregate your issue description into bullet points.

**Comment by manishdasa100** [comment]
@Ak-Shaw I have modified the activities description. Can you verify?

**Comment by YourAKShaw** [comment]
Looks decent. Waiting for your PR!
